services:
  backend:
    tty: true
    container_name: backend
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/api/node_modules
    depends_on:
      - postgres
    networks:
      - services
    environment:
      DATABASE_URL: postgresql://test:test@postgres:5432/test?schema=public

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    command: ["pnpm", "dev", "--filter", "web"]
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/web/node_modules
      - /usr/src/app/packages/ui/node_modules
    networks:
      - services
    depends_on:
      - backend

  postgres:
    tty: true
    container_name: postgres
    image: postgres:17
    restart: always
    ports:
      - "5432:5432" # Changed to standard Postgres port
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - services

volumes:
  postgres_data:

networks:
  services:
    driver: bridge
    name: services
